x, y = map(int, input().split())
p = 7 - max(x, y)
if p == 1: print('1/6')
elif p == 2: print('1/3')
elif p == 3: print('1/2')
elif p == 4: print('2/3')
elif p == 5: print('5/6')
else: print('1/1')